Hw04 lru cache
isteshkov/otus_hw pull request #6
Opened 2021-01-13 06:49 UTC by isteshkov

## Домашнее задание №4 «LRU-кэш»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-01-15 17:22 UTC, balabanovds requested changes
Спасибо! Хорошая работа.

Есть некоторые стилистические замечания по коду, а также не написаны тесты на кеш
Итого 6/10

Минимальный бал 7. Нужно доработать.
Будут вопросы - доступен в Slack

Успехов!

<https://otus.ru/teacher-lk/homework/40812/9018/>

2021-01-15 17:22 UTC, balabanovds commented on hw04_lru_cache/cache.go
> +	items    map[Key]listItem
Почему решили хранить значение, а не указатель?
Если хранить в качестве value указатель, то и разыменовавать не надо.

2021-01-15 17:22 UTC, balabanovds commented on hw04_lru_cache/cache.go
> +	return &lruCache{
А если capacity будет невалидно?

2021-01-15 17:22 UTC, balabanovds commented on hw04_lru_cache/cache.go
> +	sync.RWMutex
почему решили использовать RWMutex, а не Mutex?

2021-01-15 17:22 UTC, balabanovds commented on hw04_lru_cache/list.go
> +	l.swapEdges()
этот метод вызывается один раз, смысл выносить логику?

2021-01-16 11:31 UTC, isteshkov commented on hw04_lru_cache/list.go
> +	l.swapEdges()
Изначально использовал его в нескольких местах, потом все поменялось, а убрать забыл.. )

2021-01-18 05:01 UTC, balabanovds submitted a review, later dismissed
Спасибо за исправления.

Есть замечание по стилю кода.
Оценка 9/10

Если решите исправить, пересмотрим оценку.

2021-01-18 05:01 UTC, balabanovds commented on hw04_lru_cache/cache.go
> +		capacity = defaultCapacity
Хардкодить переменные - плохой стиль. 
Здесь Вы пишете либу, поэтому не передать значение через env или конфиг.
На мой взгляд, в данном случае лучше поменять сигнатуру экспортируемой функции..

2021-01-18 06:55 UTC, isteshkov commented on hw04_lru_cache/cache.go
> +		capacity = defaultCapacity
Когда исправлял это, я вспомнил один принцип Go, make zero value useful. Или в данном случае это не применимо? Лучше было бы вернуть ошибку о том что невалидное капасити?

2021-01-19 12:41 UTC, isteshkov commented on hw04_lru_cache/cache.go
> +		capacity = defaultCapacity
Исправил на возвращение ошибки.

2021-01-19 12:47 UTC, balabanovds approved these changes
10/10

2021-01-19 12:48 UTC, merged